apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: where-for-dinner-ingress
  namespace: server-workload
spec:
  virtualhost:
    fqdn: where-for-dinner.spaces.devframework.land
  routes:
  - conditions:
    - prefix: /
    services:
    - name: gateway-where-for-dinner
      port: 80
